[package]
name = "approxim"
version = "0.6.3"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
license = "Apache-2.0"
description = "Approximate floating point equality comparisons and assertions."
edition = "2024"

documentation = "https://docs.rs/approxim"
homepage = "https://github.com/jonaspleyer/approxim"
repository = "https://github.com/jonaspleyer/approxim"
readme = "README.md"

keywords = [
    "approximimate",
    "assert",
    "comparison",
    "equality",
    "float",
]

[package.metadata.docs.rs]
features = ["std", "num-complex", "array_impl", "tuple_impl", "ordered-float"]

[lib]
name = "approxim"

[features]
default = ["std"]
std = []
array_impl = []
tuple_impl = []

[dependencies]
num-traits = { version = "0.2.19", default-features = false }
num-complex = { version = "0.4.6", optional = true }
ordered-float = { version = "5.0", optional = true }
approx-derive = { version = "0.2.5", features = ["infer_name"] }
